In [1]:
# importing required pacakages

import csv
import time 
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import numpy as np

driver = webdriver.Chrome()

driver.get('https://tradestat.commerce.gov.in/eidb/ecntq.asp')
sno=[]
currency=[]
year=[]
n=range(1997,2020) # since we need the data of imports from 97 to 2020: it has been looped
for x in n:
    element=Select(driver.find_element_by_id('select2')) # slected from dropdown
    
    element.select_by_value(str(x))
    
    link=driver.find_element_by_id("button1")
    link.click()

    soup=BeautifulSoup(driver.page_source,'lxml')
    
    # Scraping the table
    li=[]
    for data in soup.find_all("td"): 
        m=data.get_text().strip()
        li.append(m)
    h=li[-3] # only takeing the value of indian 
    sno.append(h)
    currency.append("Rs.") 
    yr=str(x)+"-"+str(x+1)
    year.append(yr)
    
     # Going back to initial page for US $
    
    
    driver.get('https://tradestat.commerce.gov.in/eidb/ecntq.asp')
    
     # Repeating the same process as bove
    
    
    element=Select(driver.find_element_by_id('select2')) # slected from dropdown
    names=["radioval","radiousd"]
    element.select_by_value(str(x))
    we = driver.find_element_by_xpath("//input[@id='radiousd']") # selecting US $
    we.click()
    link=driver.find_element_by_id("button1")
    link.click()

    soup=BeautifulSoup(driver.page_source,'lxml')
    
   # Scraping the table
    li=[]
    for data in soup.find_all("td"): 
        m=data.get_text().strip()
        li.append(m)
    h=li[-3]
    sno.append(h)
    currency.append("US$") 
    yr=str(x)+"-"+str(x+1)
    year.append(yr)

    driver.get('https://tradestat.commerce.gov.in/eidb/ecntq.asp')
column_names=["Year","Currency","Total Exports"]
d={'Year':year,'Currency':currency,'Total Exports':sno}
df=pd.DataFrame(data=d)
df.to_csv('Total_exports.csv')

C:\Users\Balli\AppData\Local\Temp/ipykernel_8788/2585607278.py:23: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  element=Select(driver.find_element_by_id('select2')) # slected from dropdown
C:\Users\Balli\AppData\Local\Temp/ipykernel_8788/2585607278.py:27: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  link=driver.find_element_by_id("button1")
C:\Users\Balli\AppData\Local\Temp/ipykernel_8788/2585607278.py:51: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  element=Select(driver.find_element_by_id('select2')) # slected from dropdown
C:\Users\Balli\AppData\Local\Temp/ipykernel_8788/2585607278.py:54: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  we = driver.find_element_by_xpath("//input[@id='radiousd']") # selecting US $
C:\Users\Balli\AppData\Local\Temp/ipykernel_8788/2585607278.py:56: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  link=driver.find_element_by_id("button1")

In [117]:
df

         Year Currency   Total Exports
0   1997-1998      Rs.   12,927,770.02
1   1997-1998      US$       34,784.98
2   1998-1999      Rs.   13,975,315.65
3   1998-1999      US$       33,218.72
4   1999-2000      Rs.   15,956,177.56
5   1999-2000      US$       36,822.49
6   2000-2001      Rs.   20,357,101.09
7   2000-2001      US$       44,560.29
8   2001-2002      Rs.   20,901,797.34
9   2001-2002      US$       43,826.72
10  2002-2003      Rs.   25,513,727.66
11  2002-2003      US$       52,719.43
12  2003-2004      Rs.   29,336,674.75
13  2003-2004      US$       63,842.55
14  2004-2005      Rs.   37,533,952.62
15  2004-2005      US$       83,535.94
16  2005-2006      Rs.   45,641,786.15
17  2005-2006      US$      103,090.53
18  2006-2007      Rs.   57,177,928.52
19  2006-2007      US$      126,414.05
20  2007-2008      Rs.   65,586,352.18
21  2007-2008      US$      163,132.18
22  2008-2009      Rs.   84,075,505.87
23  2008-2009      US$      185,295.36
24  2009-2010      Rs.   84,553,364.38
25  2009-2010      US$      178,751.43
26  2010-2011      Rs.  113,696,426.38
27  2010-2011      US$      249,815.55
28  2011-2012      Rs.  146,595,939.96
29  2011-2012      US$      305,963.92
30  2012-2013      Rs.  163,431,828.96
31  2012-2013      US$      300,400.58
32  2013-2014      Rs.  190,501,108.86
33  2013-2014      US$      314,405.30
34  2014-2015      Rs.  189,634,841.76
35  2014-2015      US$      310,338.48
36  2015-2016      Rs.  171,638,440.44
37  2015-2016      US$      262,291.09
38  2016-2017      Rs.  184,943,355.34
39  2016-2017      US$      275,852.43
40  2017-2018      Rs.  195,651,452.80
41  2017-2018      US$      303,526.16
42  2018-2019      Rs.  230,772,619.38
43  2018-2019      US$      330,078.09
44  2019-2020      Rs.  221,985,418.10
45  2019-2020      US$      313,361.04